// src/constants/actionTypes.js
export const REQUEST_SELLER_REQUEST = 'REQUEST_SELLER_REQUEST';
export const REQUEST_SELLER_SUCCESS = 'REQUEST_SELLER_SUCCESS';
export const REQUEST_SELLER_FAIL = 'REQUEST_SELLER_FAIL';
export const GET_SELLER_REQUESTS_REQUEST = 'GET_SELLER_REQUESTS_REQUEST';
export const GET_SELLER_REQUESTS_SUCCESS = 'GET_SELLER_REQUESTS_SUCCESS';
export const GET_SELLER_REQUESTS_FAIL = 'GET_SELLER_REQUESTS_FAIL';
